name: Transform Design Tokens On Update
on:
  push:
    paths:
      - tokens.json
jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v2.5.2
        with:
          node-version: "16"
      - name: Install Node Dependencies
        run: npm install
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update design tokens
